#!/bin/bash

# Assign hostname and username
input_hostname="$(hostname)"
input_username="$(whoami)"


# Gather system information
datetime=$(date)
os="$(grep '^NAME=' /etc/os-release | cut -d= -f2 | tr -d '"') $(grep '^VERSION=' /etc/os-release | cut -d= -f2 | tr -d '"')"
uptime=$(uptime -p)
cpu=$(lshw -class processor 2>/dev/null | grep -m1 'product:' | cut -d: -f2 | xargs)
ram=$(free -h | awk '/^Mem:/ {print $2}')
disks=$(lshw -class disk 2>/dev/null | awk -F: '/product:|size:/ {gsub(/^[ \t]+/, "", $2); printf "%s ", $2} NR % 2 == 0 {print ""}')
video=$(lshw -class display 2>/dev/null | grep 'product:' | cut -d: -f2 | xargs)
gateway_ip=$(ip r | awk '/default/ {print $3}')
host_ip=$(ip route get "$gateway_ip" 2>/dev/null | awk '/src/ {print $7}')
dns_server=$(grep -m1 'nameserver' /etc/resolv.conf | awk '{print $2}')

# Gather system status
logged_in_users=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)
disk_space=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | paste -sd ", " -)
process_count=$(ps aux --no-heading | wc -l)
load_avg=$(uptime | awk -F'load average:' '{print $2}' | xargs)
listening_ports=$(ss -tuln | awk '/LISTEN/ {print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd ", " -)
ufw_status=$(sudo ufw status 2>/dev/null | head -n 1)

# Output report
echo ""
cat <<EOF
System Report for $input_hostname generated by $input_username, on $datetime

System Information
------------------
OS: $os
Uptime: $uptime
CPU: $cpu
RAM: $ram
Disk(s): $disks
Video: $video
Host Address: $host_ip
Gateway IP: $gateway_ip
DNS Server: $dns_server

System Status
-------------
Users Logged In: $logged_in_users
Disk Space: $disk_space
Process Count: $process_count
Load Averages: $load_avg
Listening Network Ports: $listening_ports
UFW Status: $ufw_status
EOF
echo ""
